apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 5000
  selector:
    name: ai-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  ai-api-deploy
  labels:
    name:  ai-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  ai-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: sivak8s.azurecr.io/sivak8s/python-flask-sklearn-docker:134
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        name:  ai-api-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
