# Default values for python.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: sivak8s.azurecr.io/sivak8s/pythonapp:v1
  tag:
  pullPolicy: IfNotPresent
service:
  name: python
  type: LoadBalancer
  externalPort: 3000
  internalPort: 5000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false
